/**
 * Swagger PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { StoreController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('StoreController', () => {
  let controller : StoreController;

  beforeAll(() => {
    controller = new StoreController(testClient);
  });

  it('should Test getInventory', async () => {
    const response = await makeApiCall(() => controller.getInventory());

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
