/**
 * Swagger PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Client, Configuration, Environment } from '../src';

const defaultTestConfiguration: Partial<Configuration> = {
  httpBasicCredentials: { username: 'test', passwprd: 'testPassword' },
};

export const testClient = new Client({
  ...createConfigurationFromEnvironment(),
  ...defaultTestConfiguration,
});

function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.SWAGGER_PETSTORE_LIB_ENVIRONMENT;
  const timeout = process.env.SWAGGER_PETSTORE_LIB_TIMEOUT;
  const testHeader = process.env.SWAGGER_PETSTORE_LIB_TEST_HEADER;
  const apiKey = process.env.SWAGGER_PETSTORE_LIB_API_KEY;
  const username = process.env.SWAGGER_PETSTORE_LIB_USERNAME;
  const passwprd = process.env.SWAGGER_PETSTORE_LIB_PASSWPRD;
  const oAuthClientId = process.env.SWAGGER_PETSTORE_LIB_O_AUTH_CLIENT_ID;
  const oAuthRedirectUri = process.env.SWAGGER_PETSTORE_LIB_O_AUTH_REDIRECT_URI;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (testHeader !== undefined) {
    config.testHeader = testHeader;
  }

  if (apiKey !== undefined) {
    config.apiKeyCredentials = { api_key: apiKey };
  }

  if (username !== undefined && passwprd !== undefined) {
    config.httpBasicCredentials = { username: username, passwprd: passwprd };
  }

  if (oAuthClientId !== undefined && oAuthRedirectUri !== undefined) {
    config.petstoreAuthCredentials = {
      oAuthClientId: oAuthClientId,
      oAuthRedirectUri: oAuthRedirectUri,
    };
  }

  return config;
}
