<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing ApiKey security credentials.
 */
class ApiKeyCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for ApiKeyCredentialsBuilder
     *
     * @param string $xAPIKey
     */
    public static function init(string $xAPIKey): self
    {
        return new self(['xAPIKey' => $xAPIKey]);
    }

    /**
     * Setter for XAPIKey.
     *
     * @param string $xAPIKey
     *
     * @return $this
     */
    public function xAPIKey(string $xAPIKey): self
    {
        $this->config['xAPIKey'] = $xAPIKey;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
