<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Authentication;

use Core\Authentication\CoreAuth;
use WebhooksAndCallbacksAPILib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class ApiKeyManager extends CoreAuth implements ApiKeyCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(HeaderParam::init('X-API-Key', $this->getXAPIKey())->requiredNonEmpty());
    }

    /**
     * String value for xAPIKey.
     */
    public function getXAPIKey(): string
    {
        return $this->config['xAPIKey'] ?? ConfigurationDefaults::X_API_KEY;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $xAPIKey API key for authentication
     */
    public function equals(string $xAPIKey): bool
    {
        return $xAPIKey == $this->getXAPIKey();
    }
}
