<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface ApiKeyCredentials
{
    /**
     * String value for xAPIKey.
     */
    public function getXAPIKey(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $xAPIKey API key for authentication
     */
    public function equals(string $xAPIKey): bool;
}
