<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreLib\Authentication;

use Core\Authentication\CoreAuth;
use SwaggerPetstoreLib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;
use Core\Utils\CoreHelper;

/**
 * Utility class for authorization and token management.
 */
class HttpBasicManager extends CoreAuth implements HttpBasicCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(HeaderParam::init(
            'Authorization',
            CoreHelper::getBasicAuthEncodedString($this->getUsername(), $this->getPasswprd())
        )->requiredNonEmpty());
    }

    /**
     * String value for username.
     */
    public function getUsername(): string
    {
        return $this->config['username'] ?? ConfigurationDefaults::USERNAME;
    }

    /**
     * String value for passwprd.
     */
    public function getPasswprd(): string
    {
        return $this->config['passwprd'] ?? ConfigurationDefaults::PASSWPRD;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $username
     * @param string $passwprd
     */
    public function equals(string $username, string $passwprd): bool
    {
        return $username == $this->getUsername() &&
            $passwprd == $this->getPasswprd();
    }
}
