<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\AuditLogEvent;

/**
 * Builder for model AuditLogEvent
 *
 * @see AuditLogEvent
 */
class AuditLogEventBuilder
{
    /**
     * @var AuditLogEvent
     */
    private $instance;

    private function __construct(AuditLogEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Audit Log Event Builder object.
     */
    public static function init(): self
    {
        return new self(new AuditLogEvent());
    }

    /**
     * Sets event Type field.
     *
     * @param string|null $value
     */
    public function eventType(?string $value): self
    {
        $this->instance->setEventType($value);
        return $this;
    }

    /**
     * Sets actor field.
     *
     * @param string|null $value
     */
    public function actor(?string $value): self
    {
        $this->instance->setActor($value);
        return $this;
    }

    /**
     * Sets action field.
     *
     * @param string|null $value
     */
    public function action(?string $value): self
    {
        $this->instance->setAction($value);
        return $this;
    }

    /**
     * Sets context field.
     *
     * @param array|null $value
     */
    public function context(?array $value): self
    {
        $this->instance->setContext($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Audit Log Event object.
     */
    public function build(): AuditLogEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
