<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\CreateOrderRequest;
use WebhooksAndCallbacksAPILib\Models\OrderItem;

/**
 * Builder for model CreateOrderRequest
 *
 * @see CreateOrderRequest
 */
class CreateOrderRequestBuilder
{
    /**
     * @var CreateOrderRequest
     */
    private $instance;

    private function __construct(CreateOrderRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Order Request Builder object.
     *
     * @param string $customerId
     * @param OrderItem[] $items
     * @param string $callbackUrl
     */
    public static function init(string $customerId, array $items, string $callbackUrl): self
    {
        return new self(new CreateOrderRequest($customerId, $items, $callbackUrl));
    }

    /**
     * Sets document field.
     *
     * @param string|null $value
     */
    public function document(?string $value): self
    {
        $this->instance->setDocument($value);
        return $this;
    }

    /**
     * Sets metadata field.
     *
     * @param array|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets attributes field.
     *
     * @param array<string,string>|null $value
     */
    public function attributes(?array $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Create Order Request object.
     */
    public function build(): CreateOrderRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
