<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\DeliveryDetails;

/**
 * Builder for model DeliveryDetails
 *
 * @see DeliveryDetails
 */
class DeliveryDetailsBuilder
{
    /**
     * @var DeliveryDetails
     */
    private $instance;

    private function __construct(DeliveryDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Delivery Details Builder object.
     */
    public static function init(): self
    {
        return new self(new DeliveryDetails());
    }

    /**
     * Sets method field.
     *
     * @param string|null $value
     */
    public function method(?string $value): self
    {
        $this->instance->setMethod($value);
        return $this;
    }

    /**
     * Sets eta field.
     *
     * @param \DateTime|null $value
     */
    public function eta(?\DateTime $value): self
    {
        $this->instance->setEta($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Delivery Details object.
     */
    public function build(): DeliveryDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
