<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\InventoryStockDecreaseEvent;

/**
 * Builder for model InventoryStockDecreaseEvent
 *
 * @see InventoryStockDecreaseEvent
 */
class InventoryStockDecreaseEventBuilder
{
    /**
     * @var InventoryStockDecreaseEvent
     */
    private $instance;

    private function __construct(InventoryStockDecreaseEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Inventory Stock Decrease Event Builder object.
     */
    public static function init(): self
    {
        return new self(new InventoryStockDecreaseEvent());
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Inventory Stock Decrease Event object.
     */
    public function build(): InventoryStockDecreaseEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
