<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\InventoryStockDepletedEvent;

/**
 * Builder for model InventoryStockDepletedEvent
 *
 * @see InventoryStockDepletedEvent
 */
class InventoryStockDepletedEventBuilder
{
    /**
     * @var InventoryStockDepletedEvent
     */
    private $instance;

    private function __construct(InventoryStockDepletedEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Inventory Stock Depleted Event Builder object.
     */
    public static function init(): self
    {
        return new self(new InventoryStockDepletedEvent());
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Inventory Stock Depleted Event object.
     */
    public function build(): InventoryStockDepletedEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
