<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\InventoryStockIncreaseEvent;

/**
 * Builder for model InventoryStockIncreaseEvent
 *
 * @see InventoryStockIncreaseEvent
 */
class InventoryStockIncreaseEventBuilder
{
    /**
     * @var InventoryStockIncreaseEvent
     */
    private $instance;

    private function __construct(InventoryStockIncreaseEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Inventory Stock Increase Event Builder object.
     */
    public static function init(): self
    {
        return new self(new InventoryStockIncreaseEvent());
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Inventory Stock Increase Event object.
     */
    public function build(): InventoryStockIncreaseEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
