<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\NotificationCallback;

/**
 * Builder for model NotificationCallback
 *
 * @see NotificationCallback
 */
class NotificationCallbackBuilder
{
    /**
     * @var NotificationCallback
     */
    private $instance;

    private function __construct(NotificationCallback $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Notification Callback Builder object.
     *
     * @param string $notificationType
     * @param string $subject
     * @param string $message
     */
    public static function init(string $notificationType, string $subject, string $message): self
    {
        return new self(new NotificationCallback($notificationType, $subject, $message));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Notification Callback object.
     */
    public function build(): NotificationCallback
    {
        return CoreHelper::clone($this->instance);
    }
}
