<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\OrderItem;

/**
 * Builder for model OrderItem
 *
 * @see OrderItem
 */
class OrderItemBuilder
{
    /**
     * @var OrderItem
     */
    private $instance;

    private function __construct(OrderItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Item Builder object.
     *
     * @param string $productId
     * @param int $quantity
     * @param float $price
     */
    public static function init(string $productId, int $quantity, float $price): self
    {
        return new self(new OrderItem($productId, $quantity, $price));
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Order Item object.
     */
    public function build(): OrderItem
    {
        return CoreHelper::clone($this->instance);
    }
}
