<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\Address;
use WebhooksAndCallbacksAPILib\Models\DeliveryDetails;
use WebhooksAndCallbacksAPILib\Models\OrderCreatedEvent;
use WebhooksAndCallbacksAPILib\Models\Package;

/**
 * Builder for model OrderCreatedEvent
 *
 * @see OrderCreatedEvent
 */
class OrderCreatedEventBuilder
{
    /**
     * @var OrderCreatedEvent
     */
    private $instance;

    private function __construct(OrderCreatedEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Created Event Builder object.
     *
     * @param string $fulfillmentStatus
     */
    public static function init(string $fulfillmentStatus): self
    {
        return new self(new OrderCreatedEvent($fulfillmentStatus));
    }

    /**
     * Sets order Id field.
     *
     * @param string|null $value
     */
    public function orderId(?string $value): self
    {
        $this->instance->setOrderId($value);
        return $this;
    }

    /**
     * Sets tracking Number field.
     *
     * @param string|null $value
     */
    public function trackingNumber(?string $value): self
    {
        $this->instance->setTrackingNumber($value);
        return $this;
    }

    /**
     * Unsets tracking Number field.
     */
    public function unsetTrackingNumber(): self
    {
        $this->instance->unsetTrackingNumber();
        return $this;
    }

    /**
     * Sets carrier field.
     *
     * @param string|null $value
     */
    public function carrier(?string $value): self
    {
        $this->instance->setCarrier($value);
        return $this;
    }

    /**
     * Sets scopes field.
     *
     * @param string[]|null $value
     */
    public function scopes(?array $value): self
    {
        $this->instance->setScopes($value);
        return $this;
    }

    /**
     * Unsets scopes field.
     */
    public function unsetScopes(): self
    {
        $this->instance->unsetScopes();
        return $this;
    }

    /**
     * Sets estimated Delivery field.
     *
     * @param \DateTime|null $value
     */
    public function estimatedDelivery(?\DateTime $value): self
    {
        $this->instance->setEstimatedDelivery($value);
        return $this;
    }

    /**
     * Sets timestamp field.
     *
     * @param \DateTime|null $value
     */
    public function timestamp(?\DateTime $value): self
    {
        $this->instance->setTimestamp($value);
        return $this;
    }

    /**
     * Sets document field.
     *
     * @param string|null $value
     */
    public function document(?string $value): self
    {
        $this->instance->setDocument($value);
        return $this;
    }

    /**
     * Sets total Weight field.
     *
     * @param float|null $value
     */
    public function totalWeight(?float $value): self
    {
        $this->instance->setTotalWeight($value);
        return $this;
    }

    /**
     * Sets price field.
     *
     * @param float|null $value
     */
    public function price(?float $value): self
    {
        $this->instance->setPrice($value);
        return $this;
    }

    /**
     * Sets quantity field.
     *
     * @param int|null $value
     */
    public function quantity(?int $value): self
    {
        $this->instance->setQuantity($value);
        return $this;
    }

    /**
     * Sets long Id field.
     *
     * @param int|null $value
     */
    public function longId(?int $value): self
    {
        $this->instance->setLongId($value);
        return $this;
    }

    /**
     * Sets fragile field.
     *
     * @param bool|null $value
     */
    public function fragile(?bool $value): self
    {
        $this->instance->setFragile($value);
        return $this;
    }

    /**
     * Sets notes field.
     *
     * @param string|null $value
     */
    public function notes(?string $value): self
    {
        $this->instance->setNotes($value);
        return $this;
    }

    /**
     * Unsets notes field.
     */
    public function unsetNotes(): self
    {
        $this->instance->unsetNotes();
        return $this;
    }

    /**
     * Sets items field.
     *
     * @param string[]|null $value
     */
    public function items(?array $value): self
    {
        $this->instance->setItems($value);
        return $this;
    }

    /**
     * Sets packages field.
     *
     * @param Package[]|null $value
     */
    public function packages(?array $value): self
    {
        $this->instance->setPackages($value);
        return $this;
    }

    /**
     * Sets address field.
     *
     * @param Address|null $value
     */
    public function address(?Address $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Sets metadata field.
     *
     * @param array|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets attributes field.
     *
     * @param array<string,string>|null $value
     */
    public function attributes(?array $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Sets delivery Details field.
     *
     * @param string|DeliveryDetails|null $value
     */
    public function deliveryDetails($value): self
    {
        $this->instance->setDeliveryDetails($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Order Created Event object.
     */
    public function build(): OrderCreatedEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
