<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\OrderUpdatedEvent;

/**
 * Builder for model OrderUpdatedEvent
 *
 * @see OrderUpdatedEvent
 */
class OrderUpdatedEventBuilder
{
    /**
     * @var OrderUpdatedEvent
     */
    private $instance;

    private function __construct(OrderUpdatedEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Updated Event Builder object.
     *
     * @param int $orderUpdatedId
     */
    public static function init(int $orderUpdatedId): self
    {
        return new self(new OrderUpdatedEvent($orderUpdatedId));
    }

    /**
     * Sets event Type field.
     *
     * @param string|null $value
     */
    public function eventType(?string $value): self
    {
        $this->instance->setEventType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Order Updated Event object.
     */
    public function build(): OrderUpdatedEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
