<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\Package;

/**
 * Builder for model Package
 *
 * @see Package
 */
class PackageBuilder
{
    /**
     * @var Package
     */
    private $instance;

    private function __construct(Package $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Package Builder object.
     */
    public static function init(): self
    {
        return new self(new Package());
    }

    /**
     * Sets package Id field.
     *
     * @param string|null $value
     */
    public function packageId(?string $value): self
    {
        $this->instance->setPackageId($value);
        return $this;
    }

    /**
     * Sets weight field.
     *
     * @param float|null $value
     */
    public function weight(?float $value): self
    {
        $this->instance->setWeight($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Package object.
     */
    public function build(): Package
    {
        return CoreHelper::clone($this->instance);
    }
}
