<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\PaymentCallback;

/**
 * Builder for model PaymentCallback
 *
 * @see PaymentCallback
 */
class PaymentCallbackBuilder
{
    /**
     * @var PaymentCallback
     */
    private $instance;

    private function __construct(PaymentCallback $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Callback Builder object.
     *
     * @param string $orderId
     * @param string $paymentStatus
     * @param string $transactionId
     */
    public static function init(string $orderId, string $paymentStatus, string $transactionId): self
    {
        return new self(new PaymentCallback($orderId, $paymentStatus, $transactionId));
    }

    /**
     * Sets amount field.
     *
     * @param float|null $value
     */
    public function amount(?float $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets timestamp field.
     *
     * @param \DateTime|null $value
     */
    public function timestamp(?\DateTime $value): self
    {
        $this->instance->setTimestamp($value);
        return $this;
    }

    /**
     * Sets failure Reason field.
     *
     * @param string|null $value
     */
    public function failureReason(?string $value): self
    {
        $this->instance->setFailureReason($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Payment Callback object.
     */
    public function build(): PaymentCallback
    {
        return CoreHelper::clone($this->instance);
    }
}
