<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\PaymentStatusUpdatedEvent;

/**
 * Builder for model PaymentStatusUpdatedEvent
 *
 * @see PaymentStatusUpdatedEvent
 */
class PaymentStatusUpdatedEventBuilder
{
    /**
     * @var PaymentStatusUpdatedEvent
     */
    private $instance;

    private function __construct(PaymentStatusUpdatedEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Status Updated Event Builder object.
     *
     * @param string $paymentStatusId
     */
    public static function init(string $paymentStatusId): self
    {
        return new self(new PaymentStatusUpdatedEvent($paymentStatusId));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Payment Status Updated Event object.
     */
    public function build(): PaymentStatusUpdatedEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
