<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\PaymentStatusCreatedEvent;

/**
 * Builder for model PaymentStatusCreatedEvent
 *
 * @see PaymentStatusCreatedEvent
 */
class PaymentStatusCreatedEventBuilder
{
    /**
     * @var PaymentStatusCreatedEvent
     */
    private $instance;

    private function __construct(PaymentStatusCreatedEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Status Created Event Builder object.
     *
     * @param string $paymentStatusCreatedId
     */
    public static function init(string $paymentStatusCreatedId): self
    {
        return new self(new PaymentStatusCreatedEvent($paymentStatusCreatedId));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Payment Status Created Event object.
     */
    public function build(): PaymentStatusCreatedEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
