<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\PaymentCompletedEvent;

/**
 * Builder for model PaymentCompletedEvent
 *
 * @see PaymentCompletedEvent
 */
class PaymentCompletedEventBuilder
{
    /**
     * @var PaymentCompletedEvent
     */
    private $instance;

    private function __construct(PaymentCompletedEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Completed Event Builder object.
     *
     * @param int $paymentId
     */
    public static function init(int $paymentId): self
    {
        return new self(new PaymentCompletedEvent($paymentId));
    }

    /**
     * Sets event Type field.
     *
     * @param string|null $value
     */
    public function eventType(?string $value): self
    {
        $this->instance->setEventType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Payment Completed Event object.
     */
    public function build(): PaymentCompletedEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
