<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\PrimitiveCollectionEvent;

/**
 * Builder for model PrimitiveCollectionEvent
 *
 * @see PrimitiveCollectionEvent
 */
class PrimitiveCollectionEventBuilder
{
    /**
     * @var PrimitiveCollectionEvent
     */
    private $instance;

    private function __construct(PrimitiveCollectionEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Primitive Collection Event Builder object.
     *
     * @param int[] $ids
     */
    public static function init(array $ids): self
    {
        return new self(new PrimitiveCollectionEvent($ids));
    }

    /**
     * Sets event Type field.
     *
     * @param string|null $value
     */
    public function eventType(?string $value): self
    {
        $this->instance->setEventType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Primitive Collection Event object.
     */
    public function build(): PrimitiveCollectionEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
