<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\SmsNotificationCallback;

/**
 * Builder for model SmsNotificationCallback
 *
 * @see SmsNotificationCallback
 */
class SmsNotificationCallbackBuilder
{
    /**
     * @var SmsNotificationCallback
     */
    private $instance;

    private function __construct(SmsNotificationCallback $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Sms Notification Callback Builder object.
     */
    public static function init(): self
    {
        return new self(new SmsNotificationCallback());
    }

    /**
     * Sets message Id field.
     *
     * @param string|null $value
     */
    public function messageId(?string $value): self
    {
        $this->instance->setMessageId($value);
        return $this;
    }

    /**
     * Sets phone Number field.
     *
     * @param string|null $value
     */
    public function phoneNumber(?string $value): self
    {
        $this->instance->setPhoneNumber($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Sms Notification Callback object.
     */
    public function build(): SmsNotificationCallback
    {
        return CoreHelper::clone($this->instance);
    }
}
