<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\SystemMaintenanceNotificationEvent;

/**
 * Builder for model SystemMaintenanceNotificationEvent
 *
 * @see SystemMaintenanceNotificationEvent
 */
class SystemMaintenanceNotificationEventBuilder
{
    /**
     * @var SystemMaintenanceNotificationEvent
     */
    private $instance;

    private function __construct(SystemMaintenanceNotificationEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new System Maintenance Notification Event Builder object.
     */
    public static function init(): self
    {
        return new self(new SystemMaintenanceNotificationEvent());
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new System Maintenance Notification Event object.
     */
    public function build(): SystemMaintenanceNotificationEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
