<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreLib\Models\Builders;

use Core\Utils\CoreHelper;
use SwaggerPetstoreLib\Models\UserRequest;

/**
 * Builder for model UserRequest
 *
 * @see UserRequest
 */
class UserRequestBuilder
{
    /**
     * @var UserRequest
     */
    private $instance;

    private function __construct(UserRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new User Request Builder object.
     */
    public static function init(): self
    {
        return new self(new UserRequest());
    }

    /**
     * Sets id field.
     *
     * @param int|null $value
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets username field.
     *
     * @param string|null $value
     */
    public function username(?string $value): self
    {
        $this->instance->setUsername($value);
        return $this;
    }

    /**
     * Sets first Name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets last Name field.
     *
     * @param string|null $value
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets password field.
     *
     * @param string|null $value
     */
    public function password(?string $value): self
    {
        $this->instance->setPassword($value);
        return $this;
    }

    /**
     * Sets phone field.
     *
     * @param string|null $value
     */
    public function phone(?string $value): self
    {
        $this->instance->setPhone($value);
        return $this;
    }

    /**
     * Sets user Status field.
     *
     * @param int|null $value
     */
    public function userStatus(?int $value): self
    {
        $this->instance->setUserStatus($value);
        return $this;
    }

    /**
     * Initializes a new User Request object.
     */
    public function build(): UserRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
