<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\UserPreferenceNotificationEvent;

/**
 * Builder for model UserPreferenceNotificationEvent
 *
 * @see UserPreferenceNotificationEvent
 */
class UserPreferenceNotificationEventBuilder
{
    /**
     * @var UserPreferenceNotificationEvent
     */
    private $instance;

    private function __construct(UserPreferenceNotificationEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new User Preference Notification Event Builder object.
     */
    public static function init(): self
    {
        return new self(new UserPreferenceNotificationEvent());
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new User Preference Notification Event object.
     */
    public function build(): UserPreferenceNotificationEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
