<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\WebhookUpdate;

/**
 * Builder for model WebhookUpdate
 *
 * @see WebhookUpdate
 */
class WebhookUpdateBuilder
{
    /**
     * @var WebhookUpdate
     */
    private $instance;

    private function __construct(WebhookUpdate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Webhook Update Builder object.
     */
    public static function init(): self
    {
        return new self(new WebhookUpdate());
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets events field.
     *
     * @param string[]|null $value
     */
    public function events(?array $value): self
    {
        $this->instance->setEvents($value);
        return $this;
    }

    /**
     * Sets secret field.
     *
     * @param string|null $value
     */
    public function secret(?string $value): self
    {
        $this->instance->setSecret($value);
        return $this;
    }

    /**
     * Sets active field.
     *
     * @param bool|null $value
     */
    public function active(?bool $value): self
    {
        $this->instance->setActive($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Webhook Update object.
     */
    public function build(): WebhookUpdate
    {
        return CoreHelper::clone($this->instance);
    }
}
