<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\Webhook;

/**
 * Builder for model Webhook
 *
 * @see Webhook
 */
class WebhookBuilder
{
    /**
     * @var Webhook
     */
    private $instance;

    private function __construct(Webhook $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Webhook Builder object.
     */
    public static function init(): self
    {
        return new self(new Webhook());
    }

    /**
     * Sets webhook Id field.
     *
     * @param string|null $value
     */
    public function webhookId(?string $value): self
    {
        $this->instance->setWebhookId($value);
        return $this;
    }

    /**
     * Sets created At field.
     *
     * @param \DateTime|null $value
     */
    public function createdAt(?\DateTime $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets updated At field.
     *
     * @param \DateTime|null $value
     */
    public function updatedAt(?\DateTime $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Sets last Delivery field.
     *
     * @param \DateTime|null $value
     */
    public function lastDelivery(?\DateTime $value): self
    {
        $this->instance->setLastDelivery($value);
        return $this;
    }

    /**
     * Sets delivery Count field.
     *
     * @param int|null $value
     */
    public function deliveryCount(?int $value): self
    {
        $this->instance->setDeliveryCount($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Webhook object.
     */
    public function build(): Webhook
    {
        return CoreHelper::clone($this->instance);
    }
}
