<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WebhooksAndCallbacksAPILib\Models\WebhookRegistration;

/**
 * Builder for model WebhookRegistration
 *
 * @see WebhookRegistration
 */
class WebhookRegistrationBuilder
{
    /**
     * @var WebhookRegistration
     */
    private $instance;

    private function __construct(WebhookRegistration $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Webhook Registration Builder object.
     *
     * @param string $url
     * @param string[] $events
     */
    public static function init(string $url, array $events): self
    {
        return new self(new WebhookRegistration($url, $events));
    }

    /**
     * Sets secret field.
     *
     * @param string|null $value
     */
    public function secret(?string $value): self
    {
        $this->instance->setSecret($value);
        return $this;
    }

    /**
     * Sets active field.
     *
     * @param bool|null $value
     */
    public function active(?bool $value): self
    {
        $this->instance->setActive($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Webhook Registration object.
     */
    public function build(): WebhookRegistration
    {
        return CoreHelper::clone($this->instance);
    }
}
