<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Events\Webhooks;

use Core\Utils\CoreHelper;
use Exception;
use Symfony\Component\HttpFoundation\Request;
use WebhooksAndCallbacksAPILib\ApiHelper;
use WebhooksAndCallbacksAPILib\Events\UnknownEvent;
use WebhooksAndCallbacksAPILib\Models\AuditLogEvent;

class WebhooksNoVerificationHandler
{
    /**
     * Parse the payload of the incoming event's request.
     *
     * @param Request $request The incoming HTTP request to be parsed.
     *
     * @return AuditLogEvent|string|int|string[]|int[]|UnknownEvent The result of the event's payload parsing.
     */
    public static function parseEvent(Request $request)
    {
        $payload = CoreHelper::deserialize($request->getContent(), false);

        try {
            return ApiHelper::getJsonHelper()->mapTypes(
                $payload,
                'oneOf(AuditLogEvent,oneOf(RootLevelPrimitiveOneOfEventRequest,int,RootLevelPri' .
                'mitiveOneOfEventRequest1[],int[]))',
                [
                    '\\WebhooksAndCallbacksAPILib\\Models\\RootLevelPrimitiveOneOfEventRequest:' .
                    ':checkValue RootLevelPrimitiveOneOfEventRequest',
                    '\\WebhooksAndCallbacksAPILib\\Models\\RootLevelPrimitiveOneOfEventRequest1' .
                    '::checkValue RootLevelPrimitiveOneOfEventRequest1[]'
                ]
            );
        } catch (Exception $_) {
            return UnknownEvent::init($payload);
        }
    }
}
