<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Events;

use Core\SignatureVerifier\VerificationFailure;
use WebhooksAndCallbacksAPILib\ApiHelper;

class SignatureVerificationFailure extends VerificationFailure
{
    /**
     * Creates an instance of the SignatureVerificationFailure type.
     *
     * @param string $errorMessage The signature verification failure reason.
     */
    public static function init(string $errorMessage): self
    {
        return new self($errorMessage);
    }

    /**
     * Converts the SignatureVerificationFailure object to a human-readable string representation.
     *
     * @return string The string representation of the SignatureVerificationFailure object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('SignatureVerificationFailure', ['errorMessage' => $this->getErrorMessage()]);
    }
}
