<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Apis;

use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;
use WebhooksAndCallbacksAPILib\Exceptions\ErrorException;
use WebhooksAndCallbacksAPILib\Http\ApiResponse;
use WebhooksAndCallbacksAPILib\Models\CreateOrderRequest;
use WebhooksAndCallbacksAPILib\Models\Order;

class OrdersApi extends BaseApi
{
    /**
     * Creates a new order and triggers callbacks for payment processing
     *
     * @param CreateOrderRequest $body
     *
     * @return ApiResponse Response from the API call
     */
    public function createOrder(CreateOrderRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/orders')
            ->auth('ApiKey', 'BearerAuth')
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body)->required());

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('400', ErrorType::init('Invalid request', ErrorException::class))
            ->type(Order::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
