<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Exceptions;

use WebhooksAndCallbacksAPILib\ApiHelper;

class ErrorException extends ApiException
{
    /**
     * @var string
     */
    private $error;

    /**
     * @var string
     */
    private $messageProperty;

    /**
     * @var array|null
     */
    private $details;

    /**
     * @param string $reason
     * @param \WebhooksAndCallbacksAPILib\Http\HttpRequest $request
     * @param \WebhooksAndCallbacksAPILib\Http\HttpResponse $response
     * @param string $error
     * @param string $messageProperty
     */
    public function __construct(
        string $reason,
        \WebhooksAndCallbacksAPILib\Http\HttpRequest $request,
        \WebhooksAndCallbacksAPILib\Http\HttpResponse $response,
        string $error,
        string $messageProperty
    ) {
        parent::__construct($reason, $request, $response);
        $this->error = $error;
        $this->messageProperty = $messageProperty;
    }

    /**
     * Returns Error.
     * Error code
     */
    public function getError(): string
    {
        return $this->error;
    }

    /**
     * Sets Error.
     * Error code
     *
     * @required
     * @maps error
     */
    public function setError(string $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Message Property.
     * Human-readable error message
     */
    public function getMessageProperty(): string
    {
        return $this->messageProperty;
    }

    /**
     * Sets Message Property.
     * Human-readable error message
     *
     * @required
     * @maps message
     */
    public function setMessageProperty(string $messageProperty): void
    {
        $this->messageProperty = $messageProperty;
    }

    /**
     * Returns Details.
     * Additional error details
     */
    public function getDetails(): ?array
    {
        return $this->details;
    }

    /**
     * Sets Details.
     * Additional error details
     *
     * @maps details
     */
    public function setDetails(?array $details): void
    {
        $this->details = $details;
    }

    /**
     * Converts the ErrorException object to a human-readable string representation.
     *
     * @return string The string representation of the ErrorException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ErrorException',
            [
                'error' => $this->error,
                'messageProperty' => $this->messageProperty,
                'details' => $this->details,
                'additionalProperties' => $this->additionalProperties
            ],
            parent::__toString()
        );
    }

    protected $propertyNames = ['error', 'message', 'details'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }
}
