/**
 * Swagger PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema.js';

export interface Category2 {
  id?: bigint;
  name?: string;
}

export const category2Schema: Schema<Category2> = object({
  id: ['id', optional(bigint())],
  name: ['name', optional(string())],
});
