<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models;

use stdClass;
use WebhooksAndCallbacksAPILib\ApiHelper;

class CreateOrderRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $customerId;

    /**
     * @var OrderItem[]
     */
    private $items;

    /**
     * @var string
     */
    private $callbackUrl;

    /**
     * @var string|null
     */
    private $document;

    /**
     * @var array|null
     */
    private $metadata;

    /**
     * @var array<string,string>|null
     */
    private $attributes;

    /**
     * @param string $customerId
     * @param OrderItem[] $items
     * @param string $callbackUrl
     */
    public function __construct(string $customerId, array $items, string $callbackUrl)
    {
        $this->customerId = $customerId;
        $this->items = $items;
        $this->callbackUrl = $callbackUrl;
    }

    /**
     * Returns Customer Id.
     * Unique identifier for the customer
     */
    public function getCustomerId(): string
    {
        return $this->customerId;
    }

    /**
     * Sets Customer Id.
     * Unique identifier for the customer
     *
     * @required
     * @maps customerId
     */
    public function setCustomerId(string $customerId): void
    {
        $this->customerId = $customerId;
    }

    /**
     * Returns Items.
     *
     * @return OrderItem[]
     */
    public function getItems(): array
    {
        return $this->items;
    }

    /**
     * Sets Items.
     *
     * @required
     * @maps items
     *
     * @param OrderItem[] $items
     */
    public function setItems(array $items): void
    {
        $this->items = $items;
    }

    /**
     * Returns Callback Url.
     * URL to receive callback notifications
     */
    public function getCallbackUrl(): string
    {
        return $this->callbackUrl;
    }

    /**
     * Sets Callback Url.
     * URL to receive callback notifications
     *
     * @required
     * @maps callbackUrl
     */
    public function setCallbackUrl(string $callbackUrl): void
    {
        $this->callbackUrl = $callbackUrl;
    }

    /**
     * Returns Document.
     * Binary file upload
     */
    public function getDocument(): ?string
    {
        return $this->document;
    }

    /**
     * Sets Document.
     * Binary file upload
     *
     * @maps document
     */
    public function setDocument(?string $document): void
    {
        $this->document = $document;
    }

    /**
     * Returns Metadata.
     * Additional order metadata
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     * Additional order metadata
     *
     * @maps metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Returns Attributes.
     *
     * @return array<string,string>|null
     */
    public function getAttributes(): ?array
    {
        return $this->attributes;
    }

    /**
     * Sets Attributes.
     *
     * @maps attributes
     *
     * @param array<string,string>|null $attributes
     */
    public function setAttributes(?array $attributes): void
    {
        $this->attributes = $attributes;
    }

    /**
     * Converts the CreateOrderRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreateOrderRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateOrderRequest',
            [
                'customerId' => $this->customerId,
                'items' => $this->items,
                'callbackUrl' => $this->callbackUrl,
                'document' => $this->document,
                'metadata' => $this->metadata,
                'attributes' => $this->attributes,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['customerId', 'items', 'callbackUrl', 'document', 'metadata', 'attributes'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['customerId']     = $this->customerId;
        $json['items']          = $this->items;
        $json['callbackUrl']    = $this->callbackUrl;
        if (isset($this->document)) {
            $json['document']   = $this->document;
        }
        if (isset($this->metadata)) {
            $json['metadata']   = $this->metadata;
        }
        if (isset($this->attributes)) {
            $json['attributes'] = $this->attributes;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
