<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models;

use stdClass;
use WebhooksAndCallbacksAPILib\ApiHelper;
use WebhooksAndCallbacksAPILib\Utils\DateTimeHelper;

class DeliveryDetails implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $method;

    /**
     * @var \DateTime|null
     */
    private $eta;

    /**
     * Returns Method.
     */
    public function getMethod(): ?string
    {
        return $this->method;
    }

    /**
     * Sets Method.
     *
     * @maps method
     */
    public function setMethod(?string $method): void
    {
        $this->method = $method;
    }

    /**
     * Returns Eta.
     */
    public function getEta(): ?\DateTime
    {
        return $this->eta;
    }

    /**
     * Sets Eta.
     *
     * @maps eta
     * @factory \WebhooksAndCallbacksAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setEta(?\DateTime $eta): void
    {
        $this->eta = $eta;
    }

    /**
     * Converts the DeliveryDetails object to a human-readable string representation.
     *
     * @return string The string representation of the DeliveryDetails object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'DeliveryDetails',
            ['method' => $this->method, 'eta' => $this->eta, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['method', 'eta'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->method)) {
            $json['method'] = $this->method;
        }
        if (isset($this->eta)) {
            $json['eta']    = DateTimeHelper::toRfc3339DateTime($this->eta);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
