<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models;

use stdClass;
use WebhooksAndCallbacksAPILib\ApiHelper;

class EmailNotificationCallback implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $messageId;

    /**
     * @var string|null
     */
    private $recipientEmail;

    /**
     * @var string|null
     */
    private $status;

    /**
     * Returns Message Id.
     */
    public function getMessageId(): ?string
    {
        return $this->messageId;
    }

    /**
     * Sets Message Id.
     *
     * @maps messageId
     */
    public function setMessageId(?string $messageId): void
    {
        $this->messageId = $messageId;
    }

    /**
     * Returns Recipient Email.
     */
    public function getRecipientEmail(): ?string
    {
        return $this->recipientEmail;
    }

    /**
     * Sets Recipient Email.
     *
     * @maps recipientEmail
     */
    public function setRecipientEmail(?string $recipientEmail): void
    {
        $this->recipientEmail = $recipientEmail;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     * @factory \WebhooksAndCallbacksAPILib\Models\Status1::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Converts the EmailNotificationCallback object to a human-readable string representation.
     *
     * @return string The string representation of the EmailNotificationCallback object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EmailNotificationCallback',
            [
                'messageId' => $this->messageId,
                'recipientEmail' => $this->recipientEmail,
                'status' => $this->status,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['messageId', 'recipientEmail', 'status'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->messageId)) {
            $json['messageId']      = $this->messageId;
        }
        if (isset($this->recipientEmail)) {
            $json['recipientEmail'] = $this->recipientEmail;
        }
        if (isset($this->status)) {
            $json['status']         = Status1::checkValue($this->status);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
