<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class Event
{
    public const ENUM_ORDERCREATED = 'order.created';

    public const ENUM_ORDERUPDATED = 'order.updated';

    public const ENUM_ORDERCANCELLED = 'order.cancelled';

    public const ENUM_PAYMENTCOMPLETED = 'payment.completed';

    public const ENUM_PAYMENTFAILED = 'payment.failed';

    public const ENUM_FULFILLMENTCOMPLETED = 'fulfillment.completed';

    private const _ALL_VALUES = [
        self::ENUM_ORDERCREATED,
        self::ENUM_ORDERUPDATED,
        self::ENUM_ORDERCANCELLED,
        self::ENUM_PAYMENTCOMPLETED,
        self::ENUM_PAYMENTFAILED,
        self::ENUM_FULFILLMENTCOMPLETED
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Event.");
    }
}
