<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models;

use stdClass;
use WebhooksAndCallbacksAPILib\ApiHelper;
use WebhooksAndCallbacksAPILib\Utils\DateTimeHelper;

class FulfillmentCallback implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $orderId;

    /**
     * @var string
     */
    private $fulfillmentStatus;

    /**
     * @var array
     */
    private $trackingNumber = [];

    /**
     * @var string|null
     */
    private $carrier;

    /**
     * @var array
     */
    private $scopes = [];

    /**
     * @var \DateTime|null
     */
    private $estimatedDelivery;

    /**
     * @var \DateTime|null
     */
    private $timestamp;

    /**
     * @var string|null
     */
    private $document;

    /**
     * @var float|null
     */
    private $totalWeight;

    /**
     * @var float|null
     */
    private $price;

    /**
     * @var int|null
     */
    private $quantity;

    /**
     * @var int|null
     */
    private $longId;

    /**
     * @var bool|null
     */
    private $fragile;

    /**
     * @var array
     */
    private $notes = [];

    /**
     * @var string[]|null
     */
    private $items;

    /**
     * @var Package[]|null
     */
    private $packages;

    /**
     * @var Address|null
     */
    private $address;

    /**
     * @var array|null
     */
    private $metadata;

    /**
     * @var array<string,string>|null
     */
    private $attributes;

    /**
     * @var string|DeliveryDetails|null
     */
    private $deliveryDetails;

    /**
     * @var array
     */
    private $orderIdd = [];

    /**
     * @var string|null
     */
    private $fulfillmentStatuss;

    /**
     * @var array
     */
    private $trackingNumberr = [];

    /**
     * @var string|null
     */
    private $carrierr;

    /**
     * @var array
     */
    private $scopess = [];

    /**
     * @var \DateTime|null
     */
    private $estimatedDeliveryy;

    /**
     * @var \DateTime|null
     */
    private $timestampp;

    /**
     * @var string|null
     */
    private $documentt;

    /**
     * @param string $fulfillmentStatus
     */
    public function __construct(string $fulfillmentStatus)
    {
        $this->fulfillmentStatus = $fulfillmentStatus;
    }

    /**
     * Returns Order Id.
     */
    public function getOrderId(): ?string
    {
        return $this->orderId;
    }

    /**
     * Sets Order Id.
     *
     * @maps orderId
     */
    public function setOrderId(?string $orderId): void
    {
        $this->orderId = $orderId;
    }

    /**
     * Returns Fulfillment Status.
     */
    public function getFulfillmentStatus(): string
    {
        return $this->fulfillmentStatus;
    }

    /**
     * Sets Fulfillment Status.
     *
     * @required
     * @maps fulfillmentStatus
     * @factory \WebhooksAndCallbacksAPILib\Models\FulfillmentStatus::checkValue
     */
    public function setFulfillmentStatus(string $fulfillmentStatus): void
    {
        $this->fulfillmentStatus = $fulfillmentStatus;
    }

    /**
     * Returns Tracking Number.
     */
    public function getTrackingNumber(): ?string
    {
        if (count($this->trackingNumber) == 0) {
            return null;
        }
        return $this->trackingNumber['value'];
    }

    /**
     * Sets Tracking Number.
     *
     * @maps trackingNumber
     */
    public function setTrackingNumber(?string $trackingNumber): void
    {
        $this->trackingNumber['value'] = $trackingNumber;
    }

    /**
     * Unsets Tracking Number.
     */
    public function unsetTrackingNumber(): void
    {
        $this->trackingNumber = [];
    }

    /**
     * Returns Carrier.
     */
    public function getCarrier(): ?string
    {
        return $this->carrier;
    }

    /**
     * Sets Carrier.
     *
     * @maps carrier
     */
    public function setCarrier(?string $carrier): void
    {
        $this->carrier = $carrier;
    }

    /**
     * Returns Scopes.
     * List of scopes that apply to the OAuth token
     *
     * @return string[]|null
     */
    public function getScopes(): ?array
    {
        if (count($this->scopes) == 0) {
            return null;
        }
        return $this->scopes['value'];
    }

    /**
     * Sets Scopes.
     * List of scopes that apply to the OAuth token
     *
     * @maps scopes
     * @factory \WebhooksAndCallbacksAPILib\Models\OauthScopeOauthACG::checkValue
     *
     * @param string[]|null $scopes
     */
    public function setScopes(?array $scopes): void
    {
        $this->scopes['value'] = $scopes;
    }

    /**
     * Unsets Scopes.
     * List of scopes that apply to the OAuth token
     */
    public function unsetScopes(): void
    {
        $this->scopes = [];
    }

    /**
     * Returns Estimated Delivery.
     */
    public function getEstimatedDelivery(): ?\DateTime
    {
        return $this->estimatedDelivery;
    }

    /**
     * Sets Estimated Delivery.
     *
     * @maps estimatedDelivery
     * @factory \WebhooksAndCallbacksAPILib\Utils\DateTimeHelper::fromSimpleDate
     */
    public function setEstimatedDelivery(?\DateTime $estimatedDelivery): void
    {
        $this->estimatedDelivery = $estimatedDelivery;
    }

    /**
     * Returns Timestamp.
     */
    public function getTimestamp(): ?\DateTime
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     *
     * @maps timestamp
     * @factory \WebhooksAndCallbacksAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTimestamp(?\DateTime $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Returns Document.
     * Binary file upload
     */
    public function getDocument(): ?string
    {
        return $this->document;
    }

    /**
     * Sets Document.
     * Binary file upload
     *
     * @maps document
     */
    public function setDocument(?string $document): void
    {
        $this->document = $document;
    }

    /**
     * Returns Total Weight.
     */
    public function getTotalWeight(): ?float
    {
        return $this->totalWeight;
    }

    /**
     * Sets Total Weight.
     *
     * @maps totalWeight
     */
    public function setTotalWeight(?float $totalWeight): void
    {
        $this->totalWeight = $totalWeight;
    }

    /**
     * Returns Price.
     */
    public function getPrice(): ?float
    {
        return $this->price;
    }

    /**
     * Sets Price.
     *
     * @maps price
     */
    public function setPrice(?float $price): void
    {
        $this->price = $price;
    }

    /**
     * Returns Quantity.
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     *
     * @maps quantity
     */
    public function setQuantity(?int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Long Id.
     */
    public function getLongId(): ?int
    {
        return $this->longId;
    }

    /**
     * Sets Long Id.
     *
     * @maps longId
     */
    public function setLongId(?int $longId): void
    {
        $this->longId = $longId;
    }

    /**
     * Returns Fragile.
     */
    public function getFragile(): ?bool
    {
        return $this->fragile;
    }

    /**
     * Sets Fragile.
     *
     * @maps fragile
     */
    public function setFragile(?bool $fragile): void
    {
        $this->fragile = $fragile;
    }

    /**
     * Returns Notes.
     * Explicitly nullable field
     */
    public function getNotes(): ?string
    {
        if (count($this->notes) == 0) {
            return null;
        }
        return $this->notes['value'];
    }

    /**
     * Sets Notes.
     * Explicitly nullable field
     *
     * @maps notes
     */
    public function setNotes(?string $notes): void
    {
        $this->notes['value'] = $notes;
    }

    /**
     * Unsets Notes.
     * Explicitly nullable field
     */
    public function unsetNotes(): void
    {
        $this->notes = [];
    }

    /**
     * Returns Items.
     *
     * @return string[]|null
     */
    public function getItems(): ?array
    {
        return $this->items;
    }

    /**
     * Sets Items.
     *
     * @maps items
     *
     * @param string[]|null $items
     */
    public function setItems(?array $items): void
    {
        $this->items = $items;
    }

    /**
     * Returns Packages.
     *
     * @return Package[]|null
     */
    public function getPackages(): ?array
    {
        return $this->packages;
    }

    /**
     * Sets Packages.
     *
     * @maps packages
     *
     * @param Package[]|null $packages
     */
    public function setPackages(?array $packages): void
    {
        $this->packages = $packages;
    }

    /**
     * Returns Address.
     */
    public function getAddress(): ?Address
    {
        return $this->address;
    }

    /**
     * Sets Address.
     *
     * @maps address
     */
    public function setAddress(?Address $address): void
    {
        $this->address = $address;
    }

    /**
     * Returns Metadata.
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     *
     * @maps metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Returns Attributes.
     *
     * @return array<string,string>|null
     */
    public function getAttributes(): ?array
    {
        return $this->attributes;
    }

    /**
     * Sets Attributes.
     *
     * @maps attributes
     *
     * @param array<string,string>|null $attributes
     */
    public function setAttributes(?array $attributes): void
    {
        $this->attributes = $attributes;
    }

    /**
     * Returns Delivery Details.
     *
     * @return string|DeliveryDetails|null
     */
    public function getDeliveryDetails()
    {
        return $this->deliveryDetails;
    }

    /**
     * Sets Delivery Details.
     *
     * @maps deliveryDetails
     * @mapsBy anyOf(oneOf(string,DeliveryDetails),null)
     *
     * @param string|DeliveryDetails|null $deliveryDetails
     */
    public function setDeliveryDetails($deliveryDetails): void
    {
        $this->deliveryDetails = $deliveryDetails;
    }

    /**
     * Returns Order Idd.
     */
    public function getOrderIdd(): ?string
    {
        if (count($this->orderIdd) == 0) {
            return null;
        }
        return $this->orderIdd['value'];
    }

    /**
     * Sets Order Idd.
     *
     * @maps orderIdd
     */
    public function setOrderIdd(?string $orderIdd): void
    {
        $this->orderIdd['value'] = $orderIdd;
    }

    /**
     * Unsets Order Idd.
     */
    public function unsetOrderIdd(): void
    {
        $this->orderIdd = [];
    }

    /**
     * Returns Fulfillment Statuss.
     */
    public function getFulfillmentStatuss(): ?string
    {
        return $this->fulfillmentStatuss;
    }

    /**
     * Sets Fulfillment Statuss.
     *
     * @maps fulfillmentStatuss
     * @factory \WebhooksAndCallbacksAPILib\Models\FulfillmentStatuss::checkValue
     */
    public function setFulfillmentStatuss(?string $fulfillmentStatuss): void
    {
        $this->fulfillmentStatuss = $fulfillmentStatuss;
    }

    /**
     * Returns Tracking Numberr.
     */
    public function getTrackingNumberr(): ?string
    {
        if (count($this->trackingNumberr) == 0) {
            return null;
        }
        return $this->trackingNumberr['value'];
    }

    /**
     * Sets Tracking Numberr.
     *
     * @maps trackingNumberr
     */
    public function setTrackingNumberr(?string $trackingNumberr): void
    {
        $this->trackingNumberr['value'] = $trackingNumberr;
    }

    /**
     * Unsets Tracking Numberr.
     */
    public function unsetTrackingNumberr(): void
    {
        $this->trackingNumberr = [];
    }

    /**
     * Returns Carrierr.
     */
    public function getCarrierr(): ?string
    {
        return $this->carrierr;
    }

    /**
     * Sets Carrierr.
     *
     * @maps carrierr
     */
    public function setCarrierr(?string $carrierr): void
    {
        $this->carrierr = $carrierr;
    }

    /**
     * Returns Scopess.
     * List of scopes that apply to the OAuth token
     *
     * @return string[]|null
     */
    public function getScopess(): ?array
    {
        if (count($this->scopess) == 0) {
            return null;
        }
        return $this->scopess['value'];
    }

    /**
     * Sets Scopess.
     * List of scopes that apply to the OAuth token
     *
     * @maps scopess
     * @factory \WebhooksAndCallbacksAPILib\Models\OauthScopeOauthACG::checkValue
     *
     * @param string[]|null $scopess
     */
    public function setScopess(?array $scopess): void
    {
        $this->scopess['value'] = $scopess;
    }

    /**
     * Unsets Scopess.
     * List of scopes that apply to the OAuth token
     */
    public function unsetScopess(): void
    {
        $this->scopess = [];
    }

    /**
     * Returns Estimated Deliveryy.
     */
    public function getEstimatedDeliveryy(): ?\DateTime
    {
        return $this->estimatedDeliveryy;
    }

    /**
     * Sets Estimated Deliveryy.
     *
     * @maps estimatedDeliveryy
     * @factory \WebhooksAndCallbacksAPILib\Utils\DateTimeHelper::fromSimpleDate
     */
    public function setEstimatedDeliveryy(?\DateTime $estimatedDeliveryy): void
    {
        $this->estimatedDeliveryy = $estimatedDeliveryy;
    }

    /**
     * Returns Timestampp.
     */
    public function getTimestampp(): ?\DateTime
    {
        return $this->timestampp;
    }

    /**
     * Sets Timestampp.
     *
     * @maps timestampp
     * @factory \WebhooksAndCallbacksAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTimestampp(?\DateTime $timestampp): void
    {
        $this->timestampp = $timestampp;
    }

    /**
     * Returns Documentt.
     * Binary file upload
     */
    public function getDocumentt(): ?string
    {
        return $this->documentt;
    }

    /**
     * Sets Documentt.
     * Binary file upload
     *
     * @maps documentt
     */
    public function setDocumentt(?string $documentt): void
    {
        $this->documentt = $documentt;
    }

    /**
     * Converts the FulfillmentCallback object to a human-readable string representation.
     *
     * @return string The string representation of the FulfillmentCallback object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'FulfillmentCallback',
            [
                'orderId' => $this->orderId,
                'fulfillmentStatus' => $this->fulfillmentStatus,
                'trackingNumber' => $this->getTrackingNumber(),
                'carrier' => $this->carrier,
                'scopes' => $this->getScopes(),
                'estimatedDelivery' => $this->estimatedDelivery,
                'timestamp' => $this->timestamp,
                'document' => $this->document,
                'totalWeight' => $this->totalWeight,
                'price' => $this->price,
                'quantity' => $this->quantity,
                'longId' => $this->longId,
                'fragile' => $this->fragile,
                'notes' => $this->getNotes(),
                'items' => $this->items,
                'packages' => $this->packages,
                'address' => $this->address,
                'metadata' => $this->metadata,
                'attributes' => $this->attributes,
                'deliveryDetails' => $this->deliveryDetails,
                'orderIdd' => $this->getOrderIdd(),
                'fulfillmentStatuss' => $this->fulfillmentStatuss,
                'trackingNumberr' => $this->getTrackingNumberr(),
                'carrierr' => $this->carrierr,
                'scopess' => $this->getScopess(),
                'estimatedDeliveryy' => $this->estimatedDeliveryy,
                'timestampp' => $this->timestampp,
                'documentt' => $this->documentt,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'orderId',
        'fulfillmentStatus',
        'trackingNumber',
        'carrier',
        'scopes',
        'estimatedDelivery',
        'timestamp',
        'document',
        'totalWeight',
        'price',
        'quantity',
        'longId',
        'fragile',
        'notes',
        'items',
        'packages',
        'address',
        'metadata',
        'attributes',
        'deliveryDetails',
        'orderIdd',
        'fulfillmentStatuss',
        'trackingNumberr',
        'carrierr',
        'scopess',
        'estimatedDeliveryy',
        'timestampp',
        'documentt'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['orderId']                = $this->orderId;
        $json['fulfillmentStatus']      = FulfillmentStatus::checkValue($this->fulfillmentStatus);
        if (!empty($this->trackingNumber)) {
            $json['trackingNumber']     = $this->trackingNumber['value'];
        }
        if (isset($this->carrier)) {
            $json['carrier']            = $this->carrier;
        }
        if (!empty($this->scopes)) {
            $json['scopes']             = OauthScopeOauthACG::checkValue($this->scopes['value']);
        }
        if (isset($this->estimatedDelivery)) {
            $json['estimatedDelivery']  = DateTimeHelper::toSimpleDate($this->estimatedDelivery);
        }
        if (isset($this->timestamp)) {
            $json['timestamp']          = DateTimeHelper::toRfc3339DateTime($this->timestamp);
        }
        if (isset($this->document)) {
            $json['document']           = $this->document;
        }
        if (isset($this->totalWeight)) {
            $json['totalWeight']        = $this->totalWeight;
        }
        if (isset($this->price)) {
            $json['price']              = $this->price;
        }
        if (isset($this->quantity)) {
            $json['quantity']           = $this->quantity;
        }
        if (isset($this->longId)) {
            $json['longId']             = $this->longId;
        }
        if (isset($this->fragile)) {
            $json['fragile']            = $this->fragile;
        }
        if (!empty($this->notes)) {
            $json['notes']              = $this->notes['value'];
        }
        if (isset($this->items)) {
            $json['items']              = $this->items;
        }
        if (isset($this->packages)) {
            $json['packages']           = $this->packages;
        }
        if (isset($this->address)) {
            $json['address']            = $this->address;
        }
        if (isset($this->metadata)) {
            $json['metadata']           = $this->metadata;
        }
        if (isset($this->attributes)) {
            $json['attributes']         = $this->attributes;
        }
        if (isset($this->deliveryDetails)) {
            $json['deliveryDetails']    =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->deliveryDetails,
                    'anyOf(oneOf(string,DeliveryDetails),null)'
                );
        }
        if (!empty($this->orderIdd)) {
            $json['orderIdd']           = $this->orderIdd['value'];
        }
        if (isset($this->fulfillmentStatuss)) {
            $json['fulfillmentStatuss'] = FulfillmentStatuss::checkValue($this->fulfillmentStatuss);
        }
        if (!empty($this->trackingNumberr)) {
            $json['trackingNumberr']    = $this->trackingNumberr['value'];
        }
        if (isset($this->carrierr)) {
            $json['carrierr']           = $this->carrierr;
        }
        if (!empty($this->scopess)) {
            $json['scopess']            = OauthScopeOauthACG::checkValue($this->scopess['value']);
        }
        if (isset($this->estimatedDeliveryy)) {
            $json['estimatedDeliveryy'] = DateTimeHelper::toSimpleDate($this->estimatedDeliveryy);
        }
        if (isset($this->timestampp)) {
            $json['timestampp']         = DateTimeHelper::toRfc3339DateTime($this->timestampp);
        }
        if (isset($this->documentt)) {
            $json['documentt']          = $this->documentt;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
