<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models;

use stdClass;
use WebhooksAndCallbacksAPILib\ApiHelper;

class NotificationCallback implements \JsonSerializable
{
    /**
     * @var string
     */
    private $notificationType;

    /**
     * @var string
     */
    private $subject;

    /**
     * @var string
     */
    private $message;

    /**
     * @param string $notificationType
     * @param string $subject
     * @param string $message
     */
    public function __construct(string $notificationType, string $subject, string $message)
    {
        $this->notificationType = $notificationType;
        $this->subject = $subject;
        $this->message = $message;
    }

    /**
     * Returns Notification Type.
     */
    public function getNotificationType(): string
    {
        return $this->notificationType;
    }

    /**
     * Sets Notification Type.
     *
     * @required
     * @maps notificationType
     */
    public function setNotificationType(string $notificationType): void
    {
        $this->notificationType = $notificationType;
    }

    /**
     * Returns Subject.
     */
    public function getSubject(): string
    {
        return $this->subject;
    }

    /**
     * Sets Subject.
     *
     * @required
     * @maps subject
     */
    public function setSubject(string $subject): void
    {
        $this->subject = $subject;
    }

    /**
     * Returns Message.
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     *
     * @required
     * @maps message
     */
    public function setMessage(string $message): void
    {
        $this->message = $message;
    }

    /**
     * Converts the NotificationCallback object to a human-readable string representation.
     *
     * @return string The string representation of the NotificationCallback object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'NotificationCallback',
            [
                'notificationType' => $this->notificationType,
                'subject' => $this->subject,
                'message' => $this->message,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['notificationType', 'subject', 'message'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['notificationType'] = $this->notificationType;
        $json['subject']          = $this->subject;
        $json['message']          = $this->message;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
