/**
 * Swagger PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OAuthScopePetstoreAuthEnum
 */
export enum OAuthScopePetstoreAuthEnum {
  Readpets = 'read:pets',
  Writepets = 'write:pets',
}

/**
 * Schema for OAuthScopePetstoreAuthEnum
 */
export const oAuthScopePetstoreAuthEnumSchema: Schema<OAuthScopePetstoreAuthEnum> = stringEnum(
  OAuthScopePetstoreAuthEnum
);
