<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models;

use stdClass;
use WebhooksAndCallbacksAPILib\ApiHelper;

class OrderUpdatedEvent implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $eventType;

    /**
     * @var int
     */
    private $orderUpdatedId;

    /**
     * @param int $orderUpdatedId
     */
    public function __construct(int $orderUpdatedId)
    {
        $this->orderUpdatedId = $orderUpdatedId;
    }

    /**
     * Returns Event Type.
     */
    public function getEventType(): ?string
    {
        return $this->eventType;
    }

    /**
     * Sets Event Type.
     *
     * @maps eventType
     * @factory \WebhooksAndCallbacksAPILib\Models\EventType::checkValue
     */
    public function setEventType(?string $eventType): void
    {
        $this->eventType = $eventType;
    }

    /**
     * Returns Order Updated Id.
     */
    public function getOrderUpdatedId(): int
    {
        return $this->orderUpdatedId;
    }

    /**
     * Sets Order Updated Id.
     *
     * @required
     * @maps orderUpdatedId
     */
    public function setOrderUpdatedId(int $orderUpdatedId): void
    {
        $this->orderUpdatedId = $orderUpdatedId;
    }

    /**
     * Converts the OrderUpdatedEvent object to a human-readable string representation.
     *
     * @return string The string representation of the OrderUpdatedEvent object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OrderUpdatedEvent',
            [
                'eventType' => $this->eventType,
                'orderUpdatedId' => $this->orderUpdatedId,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['eventType', 'orderUpdatedId'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->eventType)) {
            $json['eventType']  = EventType::checkValue($this->eventType);
        }
        $json['orderUpdatedId'] = $this->orderUpdatedId;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
