<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models;

use stdClass;
use WebhooksAndCallbacksAPILib\ApiHelper;
use WebhooksAndCallbacksAPILib\Utils\DateTimeHelper;

class PaymentCallback implements \JsonSerializable
{
    /**
     * @var string
     */
    private $orderId;

    /**
     * @var string
     */
    private $paymentStatus;

    /**
     * @var string
     */
    private $transactionId;

    /**
     * @var float|null
     */
    private $amount;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var \DateTime|null
     */
    private $timestamp;

    /**
     * @var string|null
     */
    private $failureReason;

    /**
     * @param string $orderId
     * @param string $paymentStatus
     * @param string $transactionId
     */
    public function __construct(string $orderId, string $paymentStatus, string $transactionId)
    {
        $this->orderId = $orderId;
        $this->paymentStatus = $paymentStatus;
        $this->transactionId = $transactionId;
    }

    /**
     * Returns Order Id.
     */
    public function getOrderId(): string
    {
        return $this->orderId;
    }

    /**
     * Sets Order Id.
     *
     * @required
     * @maps orderId
     */
    public function setOrderId(string $orderId): void
    {
        $this->orderId = $orderId;
    }

    /**
     * Returns Payment Status.
     */
    public function getPaymentStatus(): string
    {
        return $this->paymentStatus;
    }

    /**
     * Sets Payment Status.
     *
     * @required
     * @maps paymentStatus
     * @factory \WebhooksAndCallbacksAPILib\Models\PaymentStatus::checkValue
     */
    public function setPaymentStatus(string $paymentStatus): void
    {
        $this->paymentStatus = $paymentStatus;
    }

    /**
     * Returns Transaction Id.
     */
    public function getTransactionId(): string
    {
        return $this->transactionId;
    }

    /**
     * Sets Transaction Id.
     *
     * @required
     * @maps transactionId
     */
    public function setTransactionId(string $transactionId): void
    {
        $this->transactionId = $transactionId;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): ?float
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @maps amount
     */
    public function setAmount(?float $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Timestamp.
     */
    public function getTimestamp(): ?\DateTime
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     *
     * @maps timestamp
     * @factory \WebhooksAndCallbacksAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTimestamp(?\DateTime $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Returns Failure Reason.
     * Reason for payment failure (if applicable)
     */
    public function getFailureReason(): ?string
    {
        return $this->failureReason;
    }

    /**
     * Sets Failure Reason.
     * Reason for payment failure (if applicable)
     *
     * @maps failureReason
     */
    public function setFailureReason(?string $failureReason): void
    {
        $this->failureReason = $failureReason;
    }

    /**
     * Converts the PaymentCallback object to a human-readable string representation.
     *
     * @return string The string representation of the PaymentCallback object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaymentCallback',
            [
                'orderId' => $this->orderId,
                'paymentStatus' => $this->paymentStatus,
                'transactionId' => $this->transactionId,
                'amount' => $this->amount,
                'currency' => $this->currency,
                'timestamp' => $this->timestamp,
                'failureReason' => $this->failureReason,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'orderId',
        'paymentStatus',
        'transactionId',
        'amount',
        'currency',
        'timestamp',
        'failureReason'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['orderId']           = $this->orderId;
        $json['paymentStatus']     = PaymentStatus::checkValue($this->paymentStatus);
        $json['transactionId']     = $this->transactionId;
        if (isset($this->amount)) {
            $json['amount']        = $this->amount;
        }
        if (isset($this->currency)) {
            $json['currency']      = $this->currency;
        }
        if (isset($this->timestamp)) {
            $json['timestamp']     = DateTimeHelper::toRfc3339DateTime($this->timestamp);
        }
        if (isset($this->failureReason)) {
            $json['failureReason'] = $this->failureReason;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
