/**
 * Swagger PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Status1Enum, status1EnumSchema } from './status1Enum.js';

export interface StoreOrderRequest {
  id?: bigint;
  petId?: bigint;
  quantity?: number;
  shipDate?: string;
  status?: Status1Enum;
  complete?: boolean;
}

export const storeOrderRequestSchema: Schema<StoreOrderRequest> = object({
  id: ['id', optional(bigint())],
  petId: ['petId', optional(bigint())],
  quantity: ['quantity', optional(number())],
  shipDate: ['shipDate', optional(string())],
  status: ['status', optional(status1EnumSchema)],
  complete: ['complete', optional(boolean())],
});
