<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models;

use stdClass;
use WebhooksAndCallbacksAPILib\ApiHelper;

class WebhookUpdate implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $url;

    /**
     * @var string[]|null
     */
    private $events;

    /**
     * @var string|null
     */
    private $secret;

    /**
     * @var bool|null
     */
    private $active;

    /**
     * Returns Url.
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Events.
     *
     * @return string[]|null
     */
    public function getEvents(): ?array
    {
        return $this->events;
    }

    /**
     * Sets Events.
     *
     * @maps events
     *
     * @param string[]|null $events
     */
    public function setEvents(?array $events): void
    {
        $this->events = $events;
    }

    /**
     * Returns Secret.
     */
    public function getSecret(): ?string
    {
        return $this->secret;
    }

    /**
     * Sets Secret.
     *
     * @maps secret
     */
    public function setSecret(?string $secret): void
    {
        $this->secret = $secret;
    }

    /**
     * Returns Active.
     */
    public function getActive(): ?bool
    {
        return $this->active;
    }

    /**
     * Sets Active.
     *
     * @maps active
     */
    public function setActive(?bool $active): void
    {
        $this->active = $active;
    }

    /**
     * Converts the WebhookUpdate object to a human-readable string representation.
     *
     * @return string The string representation of the WebhookUpdate object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'WebhookUpdate',
            [
                'url' => $this->url,
                'events' => $this->events,
                'secret' => $this->secret,
                'active' => $this->active,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['url', 'events', 'secret', 'active'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->url)) {
            $json['url']    = $this->url;
        }
        if (isset($this->events)) {
            $json['events'] = $this->events;
        }
        if (isset($this->secret)) {
            $json['secret'] = $this->secret;
        }
        if (isset($this->active)) {
            $json['active'] = $this->active;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
