<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models;

use stdClass;
use WebhooksAndCallbacksAPILib\ApiHelper;

class WebhookRegistration implements \JsonSerializable
{
    /**
     * @var string
     */
    private $url;

    /**
     * @var string[]
     */
    private $events;

    /**
     * @var string|null
     */
    private $secret;

    /**
     * @var bool|null
     */
    private $active = true;

    /**
     * @param string $url
     * @param string[] $events
     */
    public function __construct(string $url, array $events)
    {
        $this->url = $url;
        $this->events = $events;
    }

    /**
     * Returns Url.
     * The endpoint URL that will receive webhook events
     */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     * The endpoint URL that will receive webhook events
     *
     * @required
     * @maps url
     */
    public function setUrl(string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Events.
     * List of events to subscribe to
     *
     * @return string[]
     */
    public function getEvents(): array
    {
        return $this->events;
    }

    /**
     * Sets Events.
     * List of events to subscribe to
     *
     * @required
     * @maps events
     * @factory \WebhooksAndCallbacksAPILib\Models\Event::checkValue
     *
     * @param string[] $events
     */
    public function setEvents(array $events): void
    {
        $this->events = $events;
    }

    /**
     * Returns Secret.
     * Secret key for webhook signature verification
     */
    public function getSecret(): ?string
    {
        return $this->secret;
    }

    /**
     * Sets Secret.
     * Secret key for webhook signature verification
     *
     * @maps secret
     */
    public function setSecret(?string $secret): void
    {
        $this->secret = $secret;
    }

    /**
     * Returns Active.
     * Whether the webhook is active
     */
    public function getActive(): ?bool
    {
        return $this->active;
    }

    /**
     * Sets Active.
     * Whether the webhook is active
     *
     * @maps active
     */
    public function setActive(?bool $active): void
    {
        $this->active = $active;
    }

    /**
     * Converts the WebhookRegistration object to a human-readable string representation.
     *
     * @return string The string representation of the WebhookRegistration object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'WebhookRegistration',
            [
                'url' => $this->url,
                'events' => $this->events,
                'secret' => $this->secret,
                'active' => $this->active,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['url', 'events', 'secret', 'active'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['url']        = $this->url;
        $json['events']     = Event::checkValue($this->events);
        if (isset($this->secret)) {
            $json['secret'] = $this->secret;
        }
        if (isset($this->active)) {
            $json['active'] = $this->active;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
