<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Models;

use stdClass;
use WebhooksAndCallbacksAPILib\ApiHelper;
use WebhooksAndCallbacksAPILib\Utils\DateTimeHelper;

class Webhook implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $webhookId;

    /**
     * @var \DateTime|null
     */
    private $createdAt;

    /**
     * @var \DateTime|null
     */
    private $updatedAt;

    /**
     * @var \DateTime|null
     */
    private $lastDelivery;

    /**
     * @var int|null
     */
    private $deliveryCount;

    /**
     * Returns Webhook Id.
     */
    public function getWebhookId(): ?string
    {
        return $this->webhookId;
    }

    /**
     * Sets Webhook Id.
     *
     * @maps webhookId
     */
    public function setWebhookId(?string $webhookId): void
    {
        $this->webhookId = $webhookId;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @maps createdAt
     * @factory \WebhooksAndCallbacksAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(?\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     *
     * @maps updatedAt
     * @factory \WebhooksAndCallbacksAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(?\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Last Delivery.
     * Timestamp of the last successful delivery
     */
    public function getLastDelivery(): ?\DateTime
    {
        return $this->lastDelivery;
    }

    /**
     * Sets Last Delivery.
     * Timestamp of the last successful delivery
     *
     * @maps lastDelivery
     * @factory \WebhooksAndCallbacksAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setLastDelivery(?\DateTime $lastDelivery): void
    {
        $this->lastDelivery = $lastDelivery;
    }

    /**
     * Returns Delivery Count.
     * Total number of events delivered
     */
    public function getDeliveryCount(): ?int
    {
        return $this->deliveryCount;
    }

    /**
     * Sets Delivery Count.
     * Total number of events delivered
     *
     * @maps deliveryCount
     */
    public function setDeliveryCount(?int $deliveryCount): void
    {
        $this->deliveryCount = $deliveryCount;
    }

    /**
     * Converts the Webhook object to a human-readable string representation.
     *
     * @return string The string representation of the Webhook object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Webhook',
            [
                'webhookId' => $this->webhookId,
                'createdAt' => $this->createdAt,
                'updatedAt' => $this->updatedAt,
                'lastDelivery' => $this->lastDelivery,
                'deliveryCount' => $this->deliveryCount,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['webhookId', 'createdAt', 'updatedAt', 'lastDelivery', 'deliveryCount'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->webhookId)) {
            $json['webhookId']     = $this->webhookId;
        }
        if (isset($this->createdAt)) {
            $json['createdAt']     = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        }
        if (isset($this->updatedAt)) {
            $json['updatedAt']     = DateTimeHelper::toRfc3339DateTime($this->updatedAt);
        }
        if (isset($this->lastDelivery)) {
            $json['lastDelivery']  = DateTimeHelper::toRfc3339DateTime($this->lastDelivery);
        }
        if (isset($this->deliveryCount)) {
            $json['deliveryCount'] = $this->deliveryCount;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
