<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib;

use CoreInterfaces\Http\HttpConfigurations;
use WebhooksAndCallbacksAPILib\Authentication\ApiKeyCredentials;
use WebhooksAndCallbacksAPILib\Authentication\ApiKeyCredentialsBuilder;
use WebhooksAndCallbacksAPILib\Authentication\BearerAuthCredentials;
use WebhooksAndCallbacksAPILib\Authentication\BearerAuthCredentialsBuilder;
use WebhooksAndCallbacksAPILib\Logging\LoggingConfigurationBuilder;
use WebhooksAndCallbacksAPILib\Proxy\ProxyConfigurationBuilder;

/**
 * An interface for all configuration parameters required by the SDK.
 */
interface ConfigurationInterface extends HttpConfigurations
{
    /**
     * Get current API environment
     */
    public function getEnvironment(): string;

    /**
     * Get the credentials to use with ApiKey
     */
    public function getApiKeyCredentials(): ApiKeyCredentials;

    /**
     * Get the credentials builder instance to update credentials for ApiKey
     */
    public function getApiKeyCredentialsBuilder(): ?ApiKeyCredentialsBuilder;

    /**
     * Get the credentials to use with BearerAuth
     */
    public function getBearerAuthCredentials(): BearerAuthCredentials;

    /**
     * Get the credentials builder instance to update credentials for BearerAuth
     */
    public function getBearerAuthCredentialsBuilder(): ?BearerAuthCredentialsBuilder;

    /**
     * Represents the logging configurations for API calls.
     */
    public function getLoggingConfigurationBuilder(): ?LoggingConfigurationBuilder;

    /**
     * Represents the proxy configurations for API calls.
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder;

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string;
}
