<?php

declare(strict_types=1);

/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WebhooksAndCallbacksAPILib\Events\Callbacks;

use Core\SignatureVerifier\HmacSignatureVerifier;
use Core\SignatureVerifier\SignatureVerifierInterface;
use Core\Utils\CoreHelper;
use Exception;
use Symfony\Component\HttpFoundation\Request;
use WebhooksAndCallbacksAPILib\ApiHelper;
use WebhooksAndCallbacksAPILib\Events\SignatureVerificationFailure;
use WebhooksAndCallbacksAPILib\Events\UnknownEvent;
use WebhooksAndCallbacksAPILib\Models\FulfillmentCallback;
use WebhooksAndCallbacksAPILib\Models\PaymentCallback;

class CallbacksAHandler
{
    /**
     * Creates a new instance of CallbacksAHandler.
     *
     * @param string $secret Your secret key for the event's signature verification.
     */
    public static function init(string $secret): self
    {
        $signatureVerifier = new HmacSignatureVerifier(
            $secret,
            [SignatureVerificationFailure::class, 'init'],
            'X-Signature',
            function (Request $request): string {
                $payload = $request->getContent();

                return "$payload";
            },
            'SHA256',
            'hex',
            '{digest}'
        );
        return new self($signatureVerifier);
    }

    private $signatureVerifier;

    private function __construct(SignatureVerifierInterface $signatureVerifier)
    {
        $this->signatureVerifier = $signatureVerifier;
    }

    /**
     * Verifies the signature of the incoming event's request.
     *
     * @param Request $request The incoming HTTP request to verify.
     *
     * @return SignatureVerificationFailure|true The result of the signature verification. 'true' when verification successful or an instance of `SignatureVerificationFailure` when verification failed.
     */
    public function verify(Request $request)
    {
        return $this->signatureVerifier->verify($request);
    }

    /**
     * Parse the payload of the incoming event's request.
     *
     * @param Request $request The incoming HTTP request to be parsed.
     *
     * @return PaymentCallback|FulfillmentCallback|UnknownEvent|SignatureVerificationFailure The result of the event's payload parsing.
     */
    public function verifyAndParseEvent(Request $request)
    {
        $signatureVerificationResult = $this->verify($request);
        if ($signatureVerificationResult instanceof SignatureVerificationFailure) {
            return $signatureVerificationResult;
        }

        $payload = CoreHelper::deserialize($request->getContent(), false);

        try {
            return ApiHelper::getJsonHelper()->mapTypes($payload, 'oneOf(PaymentCallback,FulfillmentCallback)');
        } catch (Exception $_) {
            return UnknownEvent::init($payload);
        }
    }
}
